name: Python package

on:
  push:
  schedule:
    # Runs at 2:01 UTC daily
    - cron: "1 2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install "git+https://github.com/cioos-siooc/erddap-compliance.git"
      - name: Run script
        run: sh run.sh
      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v2.0.0
        with:
          FOLDER: results
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: results # The folder the action should deploy.
